fn_args_layout = "Vertical"
fn_call_style = "Block"
force_multiline_blocks = true
max_width = 80
wrap_comments = true
generics_layout = "Vertical"
struct_lit_multiline_style = "ForceMulti"
struct_lit_style = "Block"
struct_field_align_threshold = 0
format_macro_matchers = true
format_macro_bodies = true
